
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argo
  namespace: argocd
spec:
  destination:
    namespace: argocd
    server: https://kubernetes.default.svc
  project: default
  source:
    path: charts/argo-project
    repoURL: https://github.com/codefresh-io/control-plane-cr-3379
    targetRevision: HEAD
  syncPolicy:
    automated: {}
