apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cluster-autoscaler
  namespace: argocd
spec:
  destination:
    namespace: kube-system
    server: https://kubernetes.default.svc
  project: default
  source:
    path: charts/cluster-autoscaler
    repoURL: https://github.com/codefresh-io/control-plane-cr-3379
    targetRevision: HEAD
  syncPolicy:
    automated: {}
