apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nginx-ingress
  namespace: argocd
spec:
  destination:
    namespace: default
    server: https://kubernetes.default.svc
  project: default
  source:
    path: charts/nginx-ingress
    repoURL: https://github.com/codefresh-io/control-plane-cr-3379
    targetRevision: HEAD
  syncPolicy:
    automated: {}
