argo-cd:

  global:
    image:
      repository: codefresh/argocd
      tag: v1.8.4
      imagePullPolicy: IfNotPresent

  controller:
    enableStatefulSet: true

  server:
    ingress:
      enabled: true
      annotations:
        certmanager.k8s.io/cluster-issuer: letsencrypt-prod
        kubernetes.io/ingress.class: nginx
        kubernetes.io/tls-acme: "true"
        nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
        nginx.ingress.kubernetes.io/backend-protocol: HTTP

      hosts:
        - cr-3379.cf-op.com
      paths:
        - /argocd
      extraPaths:
      tls:
        - secretName: argocd-secret
          hosts:
            - cr-3379.cf-op.com
      https: false
